version: '3'
services:
  nodejs-server:
    build:
      context: ./node-backend
      dockerfile: Dockerfile-dev
    ports:
      - "3080:3080"
    container_name: node-api
    volumes:
       - ./node-backend:/usr/src/app/api
       - /usr/src/app/api/node_modules
  angular-ui:
    build:
      context: ./angular-frontend
      dockerfile: Dockerfile-dev
    ports:
      - "4201:4201"
    container_name: angular-ui
    volumes:
       - ./angular-frontend:/usr/src/app/app-ui
       - /usr/src/app/app-ui/node_modules